// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	favorite "sea-try-go/service/favorite/api/internal/handler/favorite"
	"sea-try-go/service/favorite/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.CheckBlacklistMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/folder/create",
					Handler: favorite.CreateFavoriteFolderHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/folder/delete",
					Handler: favorite.DeleteFavoriteFolderHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/folder/list",
					Handler: favorite.GetFavoriteFoldersHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/folder/update",
					Handler: favorite.UpdateFavoriteFolderNameHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/item/create",
					Handler: favorite.CreateFavoriteHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/item/delete",
					Handler: favorite.DeleteFavoriteHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/item/list",
					Handler: favorite.GetFavoritesByFolderHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.UserAuth.AccessSecret),
		rest.WithPrefix("/favorite/v1"),
	)
}
