// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: favorite.proto

package server

import (
	"context"

	"sea-try-go/service/favorite/rpc/internal/logic"
	"sea-try-go/service/favorite/rpc/internal/svc"
	"sea-try-go/service/favorite/rpc/pb"
)

type FavoriteServiceServer struct {
	svcCtx *svc.ServiceContext
	__.UnimplementedFavoriteServiceServer
}

func NewFavoriteServiceServer(svcCtx *svc.ServiceContext) *FavoriteServiceServer {
	return &FavoriteServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *FavoriteServiceServer) CreateFavoriteFolder(ctx context.Context, in *__.CreateFavoriteFolderReq) (*__.CreateFavoriteFolderResp, error) {
	l := logic.NewCreateFavoriteFolderLogic(ctx, s.svcCtx)
	return l.CreateFavoriteFolder(in)
}

func (s *FavoriteServiceServer) CreateFavorite(ctx context.Context, in *__.CreateFavoriteReq) (*__.CreateFavoriteResp, error) {
	l := logic.NewCreateFavoriteLogic(ctx, s.svcCtx)
	return l.CreateFavorite(in)
}

func (s *FavoriteServiceServer) DeleteFavoriteFolder(ctx context.Context, in *__.DeleteFavoriteFolderReq) (*__.DeleteFavoriteFolderResp, error) {
	l := logic.NewDeleteFavoriteFolderLogic(ctx, s.svcCtx)
	return l.DeleteFavoriteFolder(in)
}

func (s *FavoriteServiceServer) DeleteFavorite(ctx context.Context, in *__.DeleteFavoriteReq) (*__.DeleteFavoriteResp, error) {
	l := logic.NewDeleteFavoriteLogic(ctx, s.svcCtx)
	return l.DeleteFavorite(in)
}

func (s *FavoriteServiceServer) UpdateFavoriteFolderName(ctx context.Context, in *__.UpdateFavoriteFolderNameReq) (*__.UpdateFavoriteFolderNameResp, error) {
	l := logic.NewUpdateFavoriteFolderNameLogic(ctx, s.svcCtx)
	return l.UpdateFavoriteFolderName(in)
}

func (s *FavoriteServiceServer) GetFavoriteFolders(ctx context.Context, in *__.GetFavoriteFoldersReq) (*__.GetFavoriteFoldersResp, error) {
	l := logic.NewGetFavoriteFoldersLogic(ctx, s.svcCtx)
	return l.GetFavoriteFolders(in)
}

func (s *FavoriteServiceServer) GetFavoritesByFolder(ctx context.Context, in *__.GetFavoritesByFolderReq) (*__.GetFavoritesByFolderResp, error) {
	l := logic.NewGetFavoritesByFolderLogic(ctx, s.svcCtx)
	return l.GetFavoritesByFolder(in)
}
