// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: favorite.proto

package favoriteservice

import (
	"context"

	"sea-try-go/service/favorite/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateFavoriteFolderReq      = __.CreateFavoriteFolderReq
	CreateFavoriteFolderResp     = __.CreateFavoriteFolderResp
	CreateFavoriteReq            = __.CreateFavoriteReq
	CreateFavoriteResp           = __.CreateFavoriteResp
	DeleteFavoriteFolderReq      = __.DeleteFavoriteFolderReq
	DeleteFavoriteFolderResp     = __.DeleteFavoriteFolderResp
	DeleteFavoriteReq            = __.DeleteFavoriteReq
	DeleteFavoriteResp           = __.DeleteFavoriteResp
	FavoriteFolder               = __.FavoriteFolder
	FavoriteItem                 = __.FavoriteItem
	GetFavoriteFoldersReq        = __.GetFavoriteFoldersReq
	GetFavoriteFoldersResp       = __.GetFavoriteFoldersResp
	GetFavoritesByFolderReq      = __.GetFavoritesByFolderReq
	GetFavoritesByFolderResp     = __.GetFavoritesByFolderResp
	UpdateFavoriteFolderNameReq  = __.UpdateFavoriteFolderNameReq
	UpdateFavoriteFolderNameResp = __.UpdateFavoriteFolderNameResp

	FavoriteService interface {
		CreateFavoriteFolder(ctx context.Context, in *CreateFavoriteFolderReq, opts ...grpc.CallOption) (*CreateFavoriteFolderResp, error)
		CreateFavorite(ctx context.Context, in *CreateFavoriteReq, opts ...grpc.CallOption) (*CreateFavoriteResp, error)
		DeleteFavoriteFolder(ctx context.Context, in *DeleteFavoriteFolderReq, opts ...grpc.CallOption) (*DeleteFavoriteFolderResp, error)
		DeleteFavorite(ctx context.Context, in *DeleteFavoriteReq, opts ...grpc.CallOption) (*DeleteFavoriteResp, error)
		UpdateFavoriteFolderName(ctx context.Context, in *UpdateFavoriteFolderNameReq, opts ...grpc.CallOption) (*UpdateFavoriteFolderNameResp, error)
		GetFavoriteFolders(ctx context.Context, in *GetFavoriteFoldersReq, opts ...grpc.CallOption) (*GetFavoriteFoldersResp, error)
		GetFavoritesByFolder(ctx context.Context, in *GetFavoritesByFolderReq, opts ...grpc.CallOption) (*GetFavoritesByFolderResp, error)
	}

	defaultFavoriteService struct {
		cli zrpc.Client
	}
)

func NewFavoriteService(cli zrpc.Client) FavoriteService {
	return &defaultFavoriteService{
		cli: cli,
	}
}

func (m *defaultFavoriteService) CreateFavoriteFolder(ctx context.Context, in *CreateFavoriteFolderReq, opts ...grpc.CallOption) (*CreateFavoriteFolderResp, error) {
	client := __.NewFavoriteServiceClient(m.cli.Conn())
	return client.CreateFavoriteFolder(ctx, in, opts...)
}

func (m *defaultFavoriteService) CreateFavorite(ctx context.Context, in *CreateFavoriteReq, opts ...grpc.CallOption) (*CreateFavoriteResp, error) {
	client := __.NewFavoriteServiceClient(m.cli.Conn())
	return client.CreateFavorite(ctx, in, opts...)
}

func (m *defaultFavoriteService) DeleteFavoriteFolder(ctx context.Context, in *DeleteFavoriteFolderReq, opts ...grpc.CallOption) (*DeleteFavoriteFolderResp, error) {
	client := __.NewFavoriteServiceClient(m.cli.Conn())
	return client.DeleteFavoriteFolder(ctx, in, opts...)
}

func (m *defaultFavoriteService) DeleteFavorite(ctx context.Context, in *DeleteFavoriteReq, opts ...grpc.CallOption) (*DeleteFavoriteResp, error) {
	client := __.NewFavoriteServiceClient(m.cli.Conn())
	return client.DeleteFavorite(ctx, in, opts...)
}

func (m *defaultFavoriteService) UpdateFavoriteFolderName(ctx context.Context, in *UpdateFavoriteFolderNameReq, opts ...grpc.CallOption) (*UpdateFavoriteFolderNameResp, error) {
	client := __.NewFavoriteServiceClient(m.cli.Conn())
	return client.UpdateFavoriteFolderName(ctx, in, opts...)
}

func (m *defaultFavoriteService) GetFavoriteFolders(ctx context.Context, in *GetFavoriteFoldersReq, opts ...grpc.CallOption) (*GetFavoriteFoldersResp, error) {
	client := __.NewFavoriteServiceClient(m.cli.Conn())
	return client.GetFavoriteFolders(ctx, in, opts...)
}

func (m *defaultFavoriteService) GetFavoritesByFolder(ctx context.Context, in *GetFavoritesByFolderReq, opts ...grpc.CallOption) (*GetFavoritesByFolderResp, error) {
	client := __.NewFavoriteServiceClient(m.cli.Conn())
	return client.GetFavoritesByFolder(ctx, in, opts...)
}
