// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: proto/hot.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 获取热门文章请求
type GetHotArticlesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopK          int32                  `protobuf:"varint,1,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"` // 返回前 K 篇，默认 20，最大 100
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHotArticlesRequest) Reset() {
	*x = GetHotArticlesRequest{}
	mi := &file_proto_hot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHotArticlesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHotArticlesRequest) ProtoMessage() {}

func (x *GetHotArticlesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHotArticlesRequest.ProtoReflect.Descriptor instead.
func (*GetHotArticlesRequest) Descriptor() ([]byte, []int) {
	return file_proto_hot_proto_rawDescGZIP(), []int{0}
}

func (x *GetHotArticlesRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

// 热门文章条目
type HotArticleItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleId     string                 `protobuf:"bytes,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	HotScore      uint32                 `protobuf:"varint,2,opt,name=hot_score,json=hotScore,proto3" json:"hot_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HotArticleItem) Reset() {
	*x = HotArticleItem{}
	mi := &file_proto_hot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HotArticleItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HotArticleItem) ProtoMessage() {}

func (x *HotArticleItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HotArticleItem.ProtoReflect.Descriptor instead.
func (*HotArticleItem) Descriptor() ([]byte, []int) {
	return file_proto_hot_proto_rawDescGZIP(), []int{1}
}

func (x *HotArticleItem) GetArticleId() string {
	if x != nil {
		return x.ArticleId
	}
	return ""
}

func (x *HotArticleItem) GetHotScore() uint32 {
	if x != nil {
		return x.HotScore
	}
	return 0
}

// 获取热门文章响应
type GetHotArticlesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*HotArticleItem      `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHotArticlesResponse) Reset() {
	*x = GetHotArticlesResponse{}
	mi := &file_proto_hot_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHotArticlesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHotArticlesResponse) ProtoMessage() {}

func (x *GetHotArticlesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hot_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHotArticlesResponse.ProtoReflect.Descriptor instead.
func (*GetHotArticlesResponse) Descriptor() ([]byte, []int) {
	return file_proto_hot_proto_rawDescGZIP(), []int{2}
}

func (x *GetHotArticlesResponse) GetItems() []*HotArticleItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// 点赞请求
type LikeArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleId     string                 `protobuf:"bytes,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeArticleRequest) Reset() {
	*x = LikeArticleRequest{}
	mi := &file_proto_hot_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeArticleRequest) ProtoMessage() {}

func (x *LikeArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hot_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeArticleRequest.ProtoReflect.Descriptor instead.
func (*LikeArticleRequest) Descriptor() ([]byte, []int) {
	return file_proto_hot_proto_rawDescGZIP(), []int{3}
}

func (x *LikeArticleRequest) GetArticleId() string {
	if x != nil {
		return x.ArticleId
	}
	return ""
}

func (x *LikeArticleRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type LikeArticleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeArticleResponse) Reset() {
	*x = LikeArticleResponse{}
	mi := &file_proto_hot_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeArticleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeArticleResponse) ProtoMessage() {}

func (x *LikeArticleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hot_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeArticleResponse.ProtoReflect.Descriptor instead.
func (*LikeArticleResponse) Descriptor() ([]byte, []int) {
	return file_proto_hot_proto_rawDescGZIP(), []int{4}
}

func (x *LikeArticleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 评论请求（评论内容由评论服务管理，此处仅触发热度事件）
type CommentArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleId     string                 `protobuf:"bytes,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentArticleRequest) Reset() {
	*x = CommentArticleRequest{}
	mi := &file_proto_hot_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentArticleRequest) ProtoMessage() {}

func (x *CommentArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hot_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentArticleRequest.ProtoReflect.Descriptor instead.
func (*CommentArticleRequest) Descriptor() ([]byte, []int) {
	return file_proto_hot_proto_rawDescGZIP(), []int{5}
}

func (x *CommentArticleRequest) GetArticleId() string {
	if x != nil {
		return x.ArticleId
	}
	return ""
}

func (x *CommentArticleRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CommentArticleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentArticleResponse) Reset() {
	*x = CommentArticleResponse{}
	mi := &file_proto_hot_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentArticleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentArticleResponse) ProtoMessage() {}

func (x *CommentArticleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hot_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentArticleResponse.ProtoReflect.Descriptor instead.
func (*CommentArticleResponse) Descriptor() ([]byte, []int) {
	return file_proto_hot_proto_rawDescGZIP(), []int{6}
}

func (x *CommentArticleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 投币请求
type CoinArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleId     string                 `protobuf:"bytes,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CoinCount     int32                  `protobuf:"varint,3,opt,name=coin_count,json=coinCount,proto3" json:"coin_count,omitempty"` // 投币数量（1 或 2）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoinArticleRequest) Reset() {
	*x = CoinArticleRequest{}
	mi := &file_proto_hot_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoinArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoinArticleRequest) ProtoMessage() {}

func (x *CoinArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hot_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoinArticleRequest.ProtoReflect.Descriptor instead.
func (*CoinArticleRequest) Descriptor() ([]byte, []int) {
	return file_proto_hot_proto_rawDescGZIP(), []int{7}
}

func (x *CoinArticleRequest) GetArticleId() string {
	if x != nil {
		return x.ArticleId
	}
	return ""
}

func (x *CoinArticleRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CoinArticleRequest) GetCoinCount() int32 {
	if x != nil {
		return x.CoinCount
	}
	return 0
}

type CoinArticleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoinArticleResponse) Reset() {
	*x = CoinArticleResponse{}
	mi := &file_proto_hot_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoinArticleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoinArticleResponse) ProtoMessage() {}

func (x *CoinArticleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hot_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoinArticleResponse.ProtoReflect.Descriptor instead.
func (*CoinArticleResponse) Descriptor() ([]byte, []int) {
	return file_proto_hot_proto_rawDescGZIP(), []int{8}
}

func (x *CoinArticleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 分享请求
type ShareArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleId     string                 `protobuf:"bytes,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Channel       string                 `protobuf:"bytes,3,opt,name=channel,proto3" json:"channel,omitempty"` // 分享渠道（"wechat" | "weibo" | "qq" | "link"）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShareArticleRequest) Reset() {
	*x = ShareArticleRequest{}
	mi := &file_proto_hot_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShareArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareArticleRequest) ProtoMessage() {}

func (x *ShareArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hot_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareArticleRequest.ProtoReflect.Descriptor instead.
func (*ShareArticleRequest) Descriptor() ([]byte, []int) {
	return file_proto_hot_proto_rawDescGZIP(), []int{9}
}

func (x *ShareArticleRequest) GetArticleId() string {
	if x != nil {
		return x.ArticleId
	}
	return ""
}

func (x *ShareArticleRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ShareArticleRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

type ShareArticleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShareArticleResponse) Reset() {
	*x = ShareArticleResponse{}
	mi := &file_proto_hot_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShareArticleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareArticleResponse) ProtoMessage() {}

func (x *ShareArticleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hot_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareArticleResponse.ProtoReflect.Descriptor instead.
func (*ShareArticleResponse) Descriptor() ([]byte, []int) {
	return file_proto_hot_proto_rawDescGZIP(), []int{10}
}

func (x *ShareArticleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_hot_proto protoreflect.FileDescriptor

const file_proto_hot_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/hot.proto\x12\x03hot\",\n" +
	"\x15GetHotArticlesRequest\x12\x13\n" +
	"\x05top_k\x18\x01 \x01(\x05R\x04topK\"L\n" +
	"\x0eHotArticleItem\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\tR\tarticleId\x12\x1b\n" +
	"\thot_score\x18\x02 \x01(\rR\bhotScore\"C\n" +
	"\x16GetHotArticlesResponse\x12)\n" +
	"\x05items\x18\x01 \x03(\v2\x13.hot.HotArticleItemR\x05items\"L\n" +
	"\x12LikeArticleRequest\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\tR\tarticleId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"/\n" +
	"\x13LikeArticleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"O\n" +
	"\x15CommentArticleRequest\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\tR\tarticleId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"2\n" +
	"\x16CommentArticleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"k\n" +
	"\x12CoinArticleRequest\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\tR\tarticleId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"coin_count\x18\x03 \x01(\x05R\tcoinCount\"/\n" +
	"\x13CoinArticleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"g\n" +
	"\x13ShareArticleRequest\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\tR\tarticleId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x18\n" +
	"\achannel\x18\x03 \x01(\tR\achannel\"0\n" +
	"\x14ShareArticleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xeb\x02\n" +
	"\n" +
	"HotService\x12I\n" +
	"\x0eGetHotArticles\x12\x1a.hot.GetHotArticlesRequest\x1a\x1b.hot.GetHotArticlesResponse\x12@\n" +
	"\vLikeArticle\x12\x17.hot.LikeArticleRequest\x1a\x18.hot.LikeArticleResponse\x12I\n" +
	"\x0eCommentArticle\x12\x1a.hot.CommentArticleRequest\x1a\x1b.hot.CommentArticleResponse\x12@\n" +
	"\vCoinArticle\x12\x17.hot.CoinArticleRequest\x1a\x18.hot.CoinArticleResponse\x12C\n" +
	"\fShareArticle\x12\x18.hot.ShareArticleRequest\x1a\x19.hot.ShareArticleResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_proto_hot_proto_rawDescOnce sync.Once
	file_proto_hot_proto_rawDescData []byte
)

func file_proto_hot_proto_rawDescGZIP() []byte {
	file_proto_hot_proto_rawDescOnce.Do(func() {
		file_proto_hot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_hot_proto_rawDesc), len(file_proto_hot_proto_rawDesc)))
	})
	return file_proto_hot_proto_rawDescData
}

var file_proto_hot_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_hot_proto_goTypes = []any{
	(*GetHotArticlesRequest)(nil),  // 0: hot.GetHotArticlesRequest
	(*HotArticleItem)(nil),         // 1: hot.HotArticleItem
	(*GetHotArticlesResponse)(nil), // 2: hot.GetHotArticlesResponse
	(*LikeArticleRequest)(nil),     // 3: hot.LikeArticleRequest
	(*LikeArticleResponse)(nil),    // 4: hot.LikeArticleResponse
	(*CommentArticleRequest)(nil),  // 5: hot.CommentArticleRequest
	(*CommentArticleResponse)(nil), // 6: hot.CommentArticleResponse
	(*CoinArticleRequest)(nil),     // 7: hot.CoinArticleRequest
	(*CoinArticleResponse)(nil),    // 8: hot.CoinArticleResponse
	(*ShareArticleRequest)(nil),    // 9: hot.ShareArticleRequest
	(*ShareArticleResponse)(nil),   // 10: hot.ShareArticleResponse
}
var file_proto_hot_proto_depIdxs = []int32{
	1,  // 0: hot.GetHotArticlesResponse.items:type_name -> hot.HotArticleItem
	0,  // 1: hot.HotService.GetHotArticles:input_type -> hot.GetHotArticlesRequest
	3,  // 2: hot.HotService.LikeArticle:input_type -> hot.LikeArticleRequest
	5,  // 3: hot.HotService.CommentArticle:input_type -> hot.CommentArticleRequest
	7,  // 4: hot.HotService.CoinArticle:input_type -> hot.CoinArticleRequest
	9,  // 5: hot.HotService.ShareArticle:input_type -> hot.ShareArticleRequest
	2,  // 6: hot.HotService.GetHotArticles:output_type -> hot.GetHotArticlesResponse
	4,  // 7: hot.HotService.LikeArticle:output_type -> hot.LikeArticleResponse
	6,  // 8: hot.HotService.CommentArticle:output_type -> hot.CommentArticleResponse
	8,  // 9: hot.HotService.CoinArticle:output_type -> hot.CoinArticleResponse
	10, // 10: hot.HotService.ShareArticle:output_type -> hot.ShareArticleResponse
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_proto_hot_proto_init() }
func file_proto_hot_proto_init() {
	if File_proto_hot_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_hot_proto_rawDesc), len(file_proto_hot_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_hot_proto_goTypes,
		DependencyIndexes: file_proto_hot_proto_depIdxs,
		MessageInfos:      file_proto_hot_proto_msgTypes,
	}.Build()
	File_proto_hot_proto = out.File
	file_proto_hot_proto_goTypes = nil
	file_proto_hot_proto_depIdxs = nil
}
