// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.19.4
// source: proto/hot.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HotService_GetHotArticles_FullMethodName = "/hot.HotService/GetHotArticles"
	HotService_LikeArticle_FullMethodName    = "/hot.HotService/LikeArticle"
	HotService_CommentArticle_FullMethodName = "/hot.HotService/CommentArticle"
	HotService_CoinArticle_FullMethodName    = "/hot.HotService/CoinArticle"
	HotService_ShareArticle_FullMethodName   = "/hot.HotService/ShareArticle"
)

// HotServiceClient is the client API for HotService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 热点服务定义
type HotServiceClient interface {
	GetHotArticles(ctx context.Context, in *GetHotArticlesRequest, opts ...grpc.CallOption) (*GetHotArticlesResponse, error)
	// 互动接口（预留，点赞/评论/投币/分享系统实现后补充逻辑）
	LikeArticle(ctx context.Context, in *LikeArticleRequest, opts ...grpc.CallOption) (*LikeArticleResponse, error)
	CommentArticle(ctx context.Context, in *CommentArticleRequest, opts ...grpc.CallOption) (*CommentArticleResponse, error)
	CoinArticle(ctx context.Context, in *CoinArticleRequest, opts ...grpc.CallOption) (*CoinArticleResponse, error)
	ShareArticle(ctx context.Context, in *ShareArticleRequest, opts ...grpc.CallOption) (*ShareArticleResponse, error)
}

type hotServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHotServiceClient(cc grpc.ClientConnInterface) HotServiceClient {
	return &hotServiceClient{cc}
}

func (c *hotServiceClient) GetHotArticles(ctx context.Context, in *GetHotArticlesRequest, opts ...grpc.CallOption) (*GetHotArticlesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHotArticlesResponse)
	err := c.cc.Invoke(ctx, HotService_GetHotArticles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hotServiceClient) LikeArticle(ctx context.Context, in *LikeArticleRequest, opts ...grpc.CallOption) (*LikeArticleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LikeArticleResponse)
	err := c.cc.Invoke(ctx, HotService_LikeArticle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hotServiceClient) CommentArticle(ctx context.Context, in *CommentArticleRequest, opts ...grpc.CallOption) (*CommentArticleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommentArticleResponse)
	err := c.cc.Invoke(ctx, HotService_CommentArticle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hotServiceClient) CoinArticle(ctx context.Context, in *CoinArticleRequest, opts ...grpc.CallOption) (*CoinArticleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CoinArticleResponse)
	err := c.cc.Invoke(ctx, HotService_CoinArticle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hotServiceClient) ShareArticle(ctx context.Context, in *ShareArticleRequest, opts ...grpc.CallOption) (*ShareArticleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShareArticleResponse)
	err := c.cc.Invoke(ctx, HotService_ShareArticle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HotServiceServer is the server API for HotService service.
// All implementations must embed UnimplementedHotServiceServer
// for forward compatibility.
//
// 热点服务定义
type HotServiceServer interface {
	GetHotArticles(context.Context, *GetHotArticlesRequest) (*GetHotArticlesResponse, error)
	// 互动接口（预留，点赞/评论/投币/分享系统实现后补充逻辑）
	LikeArticle(context.Context, *LikeArticleRequest) (*LikeArticleResponse, error)
	CommentArticle(context.Context, *CommentArticleRequest) (*CommentArticleResponse, error)
	CoinArticle(context.Context, *CoinArticleRequest) (*CoinArticleResponse, error)
	ShareArticle(context.Context, *ShareArticleRequest) (*ShareArticleResponse, error)
	mustEmbedUnimplementedHotServiceServer()
}

// UnimplementedHotServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHotServiceServer struct{}

func (UnimplementedHotServiceServer) GetHotArticles(context.Context, *GetHotArticlesRequest) (*GetHotArticlesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHotArticles not implemented")
}
func (UnimplementedHotServiceServer) LikeArticle(context.Context, *LikeArticleRequest) (*LikeArticleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LikeArticle not implemented")
}
func (UnimplementedHotServiceServer) CommentArticle(context.Context, *CommentArticleRequest) (*CommentArticleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CommentArticle not implemented")
}
func (UnimplementedHotServiceServer) CoinArticle(context.Context, *CoinArticleRequest) (*CoinArticleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CoinArticle not implemented")
}
func (UnimplementedHotServiceServer) ShareArticle(context.Context, *ShareArticleRequest) (*ShareArticleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ShareArticle not implemented")
}
func (UnimplementedHotServiceServer) mustEmbedUnimplementedHotServiceServer() {}
func (UnimplementedHotServiceServer) testEmbeddedByValue()                    {}

// UnsafeHotServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HotServiceServer will
// result in compilation errors.
type UnsafeHotServiceServer interface {
	mustEmbedUnimplementedHotServiceServer()
}

func RegisterHotServiceServer(s grpc.ServiceRegistrar, srv HotServiceServer) {
	// If the following call panics, it indicates UnimplementedHotServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HotService_ServiceDesc, srv)
}

func _HotService_GetHotArticles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHotArticlesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HotServiceServer).GetHotArticles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HotService_GetHotArticles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HotServiceServer).GetHotArticles(ctx, req.(*GetHotArticlesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HotService_LikeArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LikeArticleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HotServiceServer).LikeArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HotService_LikeArticle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HotServiceServer).LikeArticle(ctx, req.(*LikeArticleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HotService_CommentArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommentArticleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HotServiceServer).CommentArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HotService_CommentArticle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HotServiceServer).CommentArticle(ctx, req.(*CommentArticleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HotService_CoinArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoinArticleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HotServiceServer).CoinArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HotService_CoinArticle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HotServiceServer).CoinArticle(ctx, req.(*CoinArticleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HotService_ShareArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShareArticleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HotServiceServer).ShareArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HotService_ShareArticle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HotServiceServer).ShareArticle(ctx, req.(*ShareArticleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HotService_ServiceDesc is the grpc.ServiceDesc for HotService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HotService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hot.HotService",
	HandlerType: (*HotServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHotArticles",
			Handler:    _HotService_GetHotArticles_Handler,
		},
		{
			MethodName: "LikeArticle",
			Handler:    _HotService_LikeArticle_Handler,
		},
		{
			MethodName: "CommentArticle",
			Handler:    _HotService_CommentArticle_Handler,
		},
		{
			MethodName: "CoinArticle",
			Handler:    _HotService_CoinArticle_Handler,
		},
		{
			MethodName: "ShareArticle",
			Handler:    _HotService_ShareArticle_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/hot.proto",
}
