// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type GetLikeCountReq struct {
	TargetType string   `json:"target_type"`
	TargetIds  []string `json:"target_ids"`
}

type GetLikeCountResp struct {
	Counts map[string]LikeCountItem `json:"counts"`
}

type GetLikeStateReq struct {
	TargetType string   `json:"target_type"`
	TargetIds  []string `json:"target_ids"`
}

type GetLikeStateResp struct {
	States map[string]int32 `json:"states"`
}

type GetTargetLikerListReq struct {
	TargetType string `json:"target_type"`
	TargetId   string `json:"target_id"`
	Cursor     int64  `json:"cursor"`
	PageSize   int32  `json:"page_size"`
}

type GetTargetLikerListResp struct {
	List       []LikeItem `json:"list"`
	IsEnd      bool       `json:"is_end"`
	NextCursor int64      `json:"next_cursor"`
}

type GetUserLikeListReq struct {
	TargetType string `json:"target_type"`
	Cursor     int64  `json:"cursor"`
	PageSize   int32  `json:"page_size"`
}

type GetUserLikeListResp struct {
	List       []LikeRecordItem `json:"list"`
	IsEnd      bool             `json:"is_end"`
	NextCursor int64            `json:"next_cursor"`
}

type GetUserTotalLikeReq struct {
}

type GetUserTotalLikeResp struct {
	TotalLikeCount int64 `json:"total_like_count"`
}

type LikeActionReq struct {
	TargetType  string  `json:"target_type"`
	TargetId    string  `json:"target_id"`
	ActionType  int64   `json:"action_type,options=1|2|3|4"`
	AuthorId    int64   `json:"author_id,string"`
	Weight      float64 `json:"weight,optional"`
	ClientIp    string  `json:"client_ip,optional"`
	PromotionId string  `json:"promotion_id,optional"`
}

type LikeActionResp struct {
	Success      bool   `json:"success"`
	Message      string `json:"message"`
	LikeCount    int64  `json:"like_count"`
	DislikeCount int64  `json:"dislike_count"`
}

type LikeCountItem struct {
	LikeCount    int64 `json:"like_count"`
	DislikeCount int64 `json:"dislike_count"`
}

type LikeItem struct {
	UserId    int64 `json:"user_id"`
	Timestamp int64 `json:"timestamp"`
}

type LikeRecordItem struct {
	TargetType string `json:"target_type"`
	TargetId   string `json:"target_id"`
	Timestamp  int64  `json:"timestamp"`
}
