// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	like "sea-try-go/service/like/api/internal/handler/like"
	"sea-try-go/service/like/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/getlikecount",
				Handler: like.GetLikeCountHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/getlikestate",
				Handler: like.GetLikeStateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/gettargetlikerlist",
				Handler: like.GetTargetLikerListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/getuserlikelist",
				Handler: like.GetUserLikeListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/getusertotallike",
				Handler: like.GetUserTotalLikeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/likeaction",
				Handler: like.LikeActionHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.UserAuth.AccessSecret),
		rest.WithPrefix("/like/v1"),
	)
}
